# Generated by Django 3.2.7 on 2021-10-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211013_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avater',
            field=models.ImageField(default='avater.svg', null=True, upload_to=''),
        ),
    ]
